variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-22.04
    steps:
    - task: UseDotNet@2
      displayName: Install .NET 7
      inputs:
        version: 7.x

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: Install Node 18

    - script: 'yarn'
      displayName: Install Packages
      workingDirectory: templates/default/

    - script: 'yarn run build'
      displayName: Build Template
      workingDirectory: templates/default/

    - script: 'dotnet restore src/VDocFx.sln'
      displayName: Restore Packages

    - script: 'dotnet publish src/VDocFx.sln --no-restore -c $(buildConfiguration)'
      displayName: Build Project
